/* istanbul ignore file */ 

export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';